const antennaTypes=["1/4 Wave Vertical","Rybakov 25 ft (9:1)","EFHW (End Fed Half Wave)","OCF Dipole","Full Wave Loop","Fan Dipole","J-Pole","Doublet","Yagi (2–5 elements)","Extended Double Zepp","Moxon","Bobtail Curtain"];
function populateAntennaDropdown(){const sel=document.getElementById("antenna_type");sel.innerHTML="";antennaTypes.forEach(t=>{const o=document.createElement("option");o.value=t;o.textContent=t;sel.appendChild(o);});}
function init(){populateAntennaDropdown();document.getElementById("calculate_btn").addEventListener("click",calculateERP);drawPlaceholderGraphs();}
document.addEventListener("DOMContentLoaded",init);
function calculateERP(){const bandMHz=parseFloat(document.getElementById("band_mhz").value)||0;const txPower=parseFloat(document.getElementById("tx_power").value)||0;const antennaGain=parseFloat(document.getElementById("antenna_gain").value)||0;const coaxLoss=parseFloat(document.getElementById("coax_loss").value)||0;const reflectorCount=parseInt(document.getElementById("reflector_count").value||"0",10);const directorCount=parseInt(document.getElementById("director_count").value||"0",10);const radialCount=parseInt(document.getElementById("radial_count").value||"0",10);const elevatedHeight=parseFloat(document.getElementById("elevated_height").value)||0;const seaside=document.getElementById("seaside_mode").checked;const timeOfDay=document.getElementById("time_of_day").value;const erpWattsBase=txPower*Math.pow(10,(antennaGain-coaxLoss)/10);let envGainDb=0;envGainDb+=reflectorCount*0.8;envGainDb+=directorCount*0.6;if(radialCount>=16)envGainDb+=1;else if(radialCount>=8)envGainDb+=0.5;if(elevatedHeight>=2)envGainDb+=0.5;if(seaside)envGainDb+=2;if(timeOfDay==="night")envGainDb+=0.5;if(timeOfDay==="grayline")envGainDb+=1;const erpWatts=erpWattsBase*Math.pow(10,envGainDb/10);const erpDbw=10*Math.log10(erpWatts);const erpDbm=erpDbw+30;document.getElementById("summary_band").textContent=isFinite(bandMHz)?`${bandMHz.toFixed(1)} MHz`:"—";document.getElementById("summary_erp_w").textContent=isFinite(erpWatts)?erpWatts.toFixed(2):"—";document.getElementById("summary_erp_dbw").textContent=isFinite(erpDbw)?erpDbw.toFixed(2):"—";document.getElementById("summary_erp_dbm").textContent=isFinite(erpDbm)?erpDbm.toFixed(2):"—";document.getElementById("summary_eff_gain").textContent=`${envGainDb.toFixed(1)} dB env`;updateCutLengths();updateGeometrySummary();drawPlaceholderGraphs();}
function updateCutLengths(){const bands={"80m":3.5,"40m":7,"20m":14,"15m":21,"10m":28,"6m":50};Object.keys(bands).forEach(k=>{const f=bands[k];const len=71.5/f;document.getElementById(`cut_${k}`).textContent=`${len.toFixed(2)} m`;});}
function updateGeometrySummary(){const type=document.getElementById("antenna_type").value;const bandMHz=parseFloat(document.getElementById("band_mhz").value)||0;const seaside=document.getElementById("seaside_mode").checked;const reflectors=parseInt(document.getElementById("reflector_count").value||"0",10);const directors=parseInt(document.getElementById("director_count").value||"0",10);const radials=parseInt(document.getElementById("radial_count").value||"0",10);const elevatedHeight=parseFloat(document.getElementById("elevated_height").value)||0;let out=[];out.push(`Antenna: ${type}`);if(bandMHz>0)out.push(`Primary band: ${bandMHz.toFixed(1)} MHz`);if(type.includes("Yagi")||type.includes("Moxon")||type.includes("Curtain"))out.push(`Array elements: ${1+reflectors+directors} (1 driven, ${reflectors} reflector(s), ${directors} director(s))`);if(type.toLowerCase().includes("vertical")||type.toLowerCase().includes("rybakov")||type.toLowerCase().includes("j-pole"))out.push(`Radials: ${radials} (elevated: ${elevatedHeight.toFixed(1)} m)`);if(seaside)out.push("Environment: Seaside / high-conductivity ground.");document.getElementById("geometry_summary").textContent=out.join(" ");}
function drawPlaceholderGraphs(){drawPolar("azimuth_plot","Azimuth");drawPolar("elevation_plot","Elevation");drawDonut("donut_plot");}
function drawPolar(id,label){const c=document.getElementById(id);if(!c)return;const x=c.getContext("2d");const w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle="#020617";x.fillRect(0,0,w,h);x.translate(w/2,h/2);const r=Math.min(w,h)/2-16;x.strokeStyle="#1f2937";for(let rr=r;rr>0;rr-=r/4){x.beginPath();x.arc(0,0,rr,0,Math.PI*2);x.stroke();}x.strokeStyle="#111827";for(let a=0;a<360;a+=30){const rad=a*Math.PI/180;x.beginPath();x.moveTo(0,0);x.lineTo(r*Math.cos(rad),r*Math.sin(rad));x.stroke();}x.strokeStyle="#3b82f6";x.lineWidth=2;x.beginPath();for(let a=0;a<=360;a+=5){const rad=a*Math.PI/180;const mod=0.6+0.35*Math.cos(2*rad);const rr=r*mod;const xx=rr*Math.cos(rad);const yy=rr*Math.sin(rad);if(a===0)x.moveTo(xx,yy);else x.lineTo(xx,yy);}x.closePath();x.stroke();x.fillStyle="#9ca3af";x.font="10px system-ui";x.textAlign="center";x.textBaseline="bottom";x.fillText(label,0,r+10);x.setTransform(1,0,0,1,0,0);}
function drawDonut(id){const c=document.getElementById(id);if(!c)return;const x=c.getContext("2d");const w=c.width,h=c.height;x.clearRect(0,0,w,h);const cx=w/2,cy=h/2;const outer=Math.min(w,h)/2-10;const inner=outer*0.45;const g=x.createRadialGradient(cx,cy,inner,cx,cy,outer);g.addColorStop(0,"#1d4ed8");g.addColorStop(0.5,"#3b82f6");g.addColorStop(1,"#020617");x.fillStyle=g;x.beginPath();x.arc(cx,cy,outer,0,Math.PI*2);x.arc(cx,cy,inner,0,Math.PI*2,true);x.closePath();x.fill();x.strokeStyle="#0f172a";x.stroke();x.fillStyle="#e5e7eb";x.font="10px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText("3D donut (conceptual)",cx,cy);}

